apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: maxefi/auth
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-auth-secret
                  key: MONGO_AUTH_KEY
            - name: AUTH_PGUSER
              value: postgres
            - name: AUTH_PGHOST
              value: auth-postgres-srv
            - name: AUTH_PGPORT
              value: "5432"
            - name: AUTH_PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespassword
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
