apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpost-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogpost
  template:
    metadata:
      labels:
        app: blogpost
    spec:
      containers:
        - name: blogpost
          image: maxefi/blogpost
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 700Mi
              cpu: 200m
            limits:
              memory: 700Mi
              cpu: 200m
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: blogpost-srv
spec:
  selector:
    app: blogpost
  ports:
    - name: blogpost
      protocol: TCP
      port: 3000
      targetPort: 3000
