apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-container-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-container
  template:
    metadata:
      labels:
        app: client-container
    spec:
      containers:
        - name: client-container
          image: maxefi/fe-container
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: client-container-srv
spec:
  selector:
    app: client-container
  ports:
    - name: client-container
      protocol: TCP
      port: 3000
      targetPort: 8080
