apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticket.dev
      http:
        paths:
          - path: /api/v1/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /api/v1/profile/?(.*)
            backend:
              serviceName: profile-srv
              servicePort: 3000
          - path: /api/v1/newsitem/?(.*)
            backend:
              serviceName: newsitem-srv
              servicePort: 3000
          - path: /api/v1/blogpost/?(.*)
            backend:
              serviceName: blogpost-srv
              servicePort: 3000
          - path: /api/v1/group/?(.*)
            backend:
              serviceName: group-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-container-srv
              servicePort: 3000
