apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin-username"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "admin-password"
        image: mongo-express:latest
        imagePullPolicy: IfNotPresent
        name: mongo-express
        ports:
        - containerPort: 8081
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 30250
    protocol: TCP
  selector:
    app: mongo-express
  type: LoadBalancer