apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
        - name: team
          image: maxefi/team
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: team-srv
spec:
  selector:
    app: team
  ports:
    - name: team
      protocol: TCP
      port: 3000
      targetPort: 3000
