name: tests-newsitem

on:
  pull_request:
    paths:
      - 'newsitem/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd newsitem && npm install && npm run test:ci
     
    
